/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FSLedger
 * A highly customizable personal ledger based on the Flow & Stock model.
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  Error,
  StockData,
  StockID,
  Stocks,
  TagData,
  TagID,
  Tags,
  TransactionData,
  TransactionID
} from './model';

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * A health check endpoint for docker.
 * @summary Health Check
 */
export const healthCheck = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {


    return axios.default.get(
      `/api/health`,options
    );
  }




export const getHealthCheckQueryKey = () => {
    return [
    `/api/health`
    ] as const;
    }


export const getHealthCheckQueryOptions = <TData = Awaited<ReturnType<typeof healthCheck>>, TError = AxiosError<Error>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({ signal }) => healthCheck({ signal, ...axiosOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HealthCheckQueryResult = NonNullable<Awaited<ReturnType<typeof healthCheck>>>
export type HealthCheckQueryError = AxiosError<Error>


export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = AxiosError<Error>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthCheck>>,
          TError,
          Awaited<ReturnType<typeof healthCheck>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthCheck>>,
          TError,
          Awaited<ReturnType<typeof healthCheck>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Health Check
 */

export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHealthCheckQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * Get all stocks' id and name.
 * @summary List
 */
export const listStocks = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Stocks>> => {


    return axios.default.get(
      `/api/stocks`,options
    );
  }




export const getListStocksQueryKey = () => {
    return [
    `/api/stocks`
    ] as const;
    }


export const getListStocksQueryOptions = <TData = Awaited<ReturnType<typeof listStocks>>, TError = AxiosError<Error>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStocks>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListStocksQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listStocks>>> = ({ signal }) => listStocks({ signal, ...axiosOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listStocks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListStocksQueryResult = NonNullable<Awaited<ReturnType<typeof listStocks>>>
export type ListStocksQueryError = AxiosError<Error>


export function useListStocks<TData = Awaited<ReturnType<typeof listStocks>>, TError = AxiosError<Error>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStocks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listStocks>>,
          TError,
          Awaited<ReturnType<typeof listStocks>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListStocks<TData = Awaited<ReturnType<typeof listStocks>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStocks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listStocks>>,
          TError,
          Awaited<ReturnType<typeof listStocks>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListStocks<TData = Awaited<ReturnType<typeof listStocks>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStocks>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List
 */

export function useListStocks<TData = Awaited<ReturnType<typeof listStocks>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStocks>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListStocksQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * Create new stock then get created stock id.
 * @summary Create
 */
export const createStock = (
    stockData: StockData, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<StockID>> => {


    return axios.default.post(
      `/api/stocks`,
      stockData,options
    );
  }




export const getCreateStockMutationOptions = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createStock>>, TError,CreateStockMutationVariables, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createStock>>, TError,CreateStockMutationVariables, TContext> => {

const mutationKey = ['createStock'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createStock>>, CreateStockMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  createStock(data,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateStockMutationResult = NonNullable<Awaited<ReturnType<typeof createStock>>>
    export type CreateStockMutationBody = StockData
    export type CreateStockMutationError = AxiosError<Error>
    export type CreateStockMutationVariables = {data: StockData}

    /**
 * @summary Create
 */
export const useCreateStock = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createStock>>, TError,CreateStockMutationVariables, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createStock>>,
        TError,
        CreateStockMutationVariables,
        TContext
      > => {
      return useMutation(getCreateStockMutationOptions(options), queryClient);
    }

/**
 * Get stock details.
 * @summary Get
 */
export const getStock = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<StockData>> => {


    return axios.default.get(
      `/api/stocks/${id}`,options
    );
  }




export const getGetStockQueryKey = (id: string,) => {
    return [
    `/api/stocks/${id}`
    ] as const;
    }


export const getGetStockQueryOptions = <TData = Awaited<ReturnType<typeof getStock>>, TError = AxiosError<Error>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStock>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStockQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStock>>> = ({ signal }) => getStock(id, { signal, ...axiosOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStock>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStockQueryResult = NonNullable<Awaited<ReturnType<typeof getStock>>>
export type GetStockQueryError = AxiosError<Error>


export function useGetStock<TData = Awaited<ReturnType<typeof getStock>>, TError = AxiosError<Error>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStock>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStock>>,
          TError,
          Awaited<ReturnType<typeof getStock>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStock<TData = Awaited<ReturnType<typeof getStock>>, TError = AxiosError<Error>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStock>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStock>>,
          TError,
          Awaited<ReturnType<typeof getStock>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStock<TData = Awaited<ReturnType<typeof getStock>>, TError = AxiosError<Error>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStock>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get
 */

export function useGetStock<TData = Awaited<ReturnType<typeof getStock>>, TError = AxiosError<Error>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStock>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStockQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * Change a stock.
 * @summary Update
 */
export const updateStock = (
    id: string,
    stockData: StockData, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {


    return axios.default.put(
      `/api/stocks/${id}`,
      stockData,options
    );
  }




export const getUpdateStockMutationOptions = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateStock>>, TError,UpdateStockMutationVariables, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateStock>>, TError,UpdateStockMutationVariables, TContext> => {

const mutationKey = ['updateStock'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateStock>>, UpdateStockMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  updateStock(id,data,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateStockMutationResult = NonNullable<Awaited<ReturnType<typeof updateStock>>>
    export type UpdateStockMutationBody = StockData
    export type UpdateStockMutationError = AxiosError<Error>
    export type UpdateStockMutationVariables = {id: string;data: StockData}

    /**
 * @summary Update
 */
export const useUpdateStock = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateStock>>, TError,UpdateStockMutationVariables, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateStock>>,
        TError,
        UpdateStockMutationVariables,
        TContext
      > => {
      return useMutation(getUpdateStockMutationOptions(options), queryClient);
    }

/**
 * Delete a stock.
 * @summary Delete
 */
export const deleteStock = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {


    return axios.default.delete(
      `/api/stocks/${id}`,options
    );
  }




export const getDeleteStockMutationOptions = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteStock>>, TError,DeleteStockMutationVariables, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteStock>>, TError,DeleteStockMutationVariables, TContext> => {

const mutationKey = ['deleteStock'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteStock>>, DeleteStockMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  deleteStock(id,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteStockMutationResult = NonNullable<Awaited<ReturnType<typeof deleteStock>>>

    export type DeleteStockMutationError = AxiosError<Error>
    export type DeleteStockMutationVariables = {id: string}

    /**
 * @summary Delete
 */
export const useDeleteStock = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteStock>>, TError,DeleteStockMutationVariables, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteStock>>,
        TError,
        DeleteStockMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteStockMutationOptions(options), queryClient);
    }

/**
 * Get all tags.
 * @summary List
 */
export const listStockTags = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Tags>> => {


    return axios.default.get(
      `/api/stocks/tags`,options
    );
  }




export const getListStockTagsQueryKey = () => {
    return [
    `/api/stocks/tags`
    ] as const;
    }


export const getListStockTagsQueryOptions = <TData = Awaited<ReturnType<typeof listStockTags>>, TError = AxiosError<Error>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStockTags>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListStockTagsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listStockTags>>> = ({ signal }) => listStockTags({ signal, ...axiosOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listStockTags>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListStockTagsQueryResult = NonNullable<Awaited<ReturnType<typeof listStockTags>>>
export type ListStockTagsQueryError = AxiosError<Error>


export function useListStockTags<TData = Awaited<ReturnType<typeof listStockTags>>, TError = AxiosError<Error>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStockTags>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listStockTags>>,
          TError,
          Awaited<ReturnType<typeof listStockTags>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListStockTags<TData = Awaited<ReturnType<typeof listStockTags>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStockTags>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listStockTags>>,
          TError,
          Awaited<ReturnType<typeof listStockTags>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListStockTags<TData = Awaited<ReturnType<typeof listStockTags>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStockTags>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List
 */

export function useListStockTags<TData = Awaited<ReturnType<typeof listStockTags>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStockTags>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListStockTagsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * Create a new tag.
 * @summary Create
 */
export const createStockTag = (
    tagData: TagData, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TagID>> => {


    return axios.default.post(
      `/api/stocks/tags`,
      tagData,options
    );
  }




export const getCreateStockTagMutationOptions = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createStockTag>>, TError,CreateStockTagMutationVariables, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createStockTag>>, TError,CreateStockTagMutationVariables, TContext> => {

const mutationKey = ['createStockTag'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createStockTag>>, CreateStockTagMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  createStockTag(data,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateStockTagMutationResult = NonNullable<Awaited<ReturnType<typeof createStockTag>>>
    export type CreateStockTagMutationBody = TagData
    export type CreateStockTagMutationError = AxiosError<Error>
    export type CreateStockTagMutationVariables = {data: TagData}

    /**
 * @summary Create
 */
export const useCreateStockTag = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createStockTag>>, TError,CreateStockTagMutationVariables, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createStockTag>>,
        TError,
        CreateStockTagMutationVariables,
        TContext
      > => {
      return useMutation(getCreateStockTagMutationOptions(options), queryClient);
    }

/**
 * Get a tag.
 * @summary Get
 */
export const getStockTag = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TagData>> => {


    return axios.default.get(
      `/api/stocks/tags/${id}`,options
    );
  }




export const getGetStockTagQueryKey = (id: string,) => {
    return [
    `/api/stocks/tags/${id}`
    ] as const;
    }


export const getGetStockTagQueryOptions = <TData = Awaited<ReturnType<typeof getStockTag>>, TError = AxiosError<Error>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStockTag>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStockTagQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStockTag>>> = ({ signal }) => getStockTag(id, { signal, ...axiosOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStockTag>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStockTagQueryResult = NonNullable<Awaited<ReturnType<typeof getStockTag>>>
export type GetStockTagQueryError = AxiosError<Error>


export function useGetStockTag<TData = Awaited<ReturnType<typeof getStockTag>>, TError = AxiosError<Error>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStockTag>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStockTag>>,
          TError,
          Awaited<ReturnType<typeof getStockTag>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStockTag<TData = Awaited<ReturnType<typeof getStockTag>>, TError = AxiosError<Error>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStockTag>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStockTag>>,
          TError,
          Awaited<ReturnType<typeof getStockTag>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStockTag<TData = Awaited<ReturnType<typeof getStockTag>>, TError = AxiosError<Error>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStockTag>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get
 */

export function useGetStockTag<TData = Awaited<ReturnType<typeof getStockTag>>, TError = AxiosError<Error>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStockTag>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStockTagQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * Change a tag.
 * @summary Update
 */
export const updateStockTag = (
    id: string,
    tagData: TagData, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {


    return axios.default.put(
      `/api/stocks/tags/${id}`,
      tagData,options
    );
  }




export const getUpdateStockTagMutationOptions = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateStockTag>>, TError,UpdateStockTagMutationVariables, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateStockTag>>, TError,UpdateStockTagMutationVariables, TContext> => {

const mutationKey = ['updateStockTag'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateStockTag>>, UpdateStockTagMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  updateStockTag(id,data,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateStockTagMutationResult = NonNullable<Awaited<ReturnType<typeof updateStockTag>>>
    export type UpdateStockTagMutationBody = TagData
    export type UpdateStockTagMutationError = AxiosError<Error>
    export type UpdateStockTagMutationVariables = {id: string;data: TagData}

    /**
 * @summary Update
 */
export const useUpdateStockTag = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateStockTag>>, TError,UpdateStockTagMutationVariables, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateStockTag>>,
        TError,
        UpdateStockTagMutationVariables,
        TContext
      > => {
      return useMutation(getUpdateStockTagMutationOptions(options), queryClient);
    }

/**
 * Delete a tag.
 * @summary Delete
 */
export const deleteStockTag = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {


    return axios.default.delete(
      `/api/stocks/tags/${id}`,options
    );
  }




export const getDeleteStockTagMutationOptions = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteStockTag>>, TError,DeleteStockTagMutationVariables, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteStockTag>>, TError,DeleteStockTagMutationVariables, TContext> => {

const mutationKey = ['deleteStockTag'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteStockTag>>, DeleteStockTagMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  deleteStockTag(id,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteStockTagMutationResult = NonNullable<Awaited<ReturnType<typeof deleteStockTag>>>

    export type DeleteStockTagMutationError = AxiosError<Error>
    export type DeleteStockTagMutationVariables = {id: string}

    /**
 * @summary Delete
 */
export const useDeleteStockTag = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteStockTag>>, TError,DeleteStockTagMutationVariables, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteStockTag>>,
        TError,
        DeleteStockTagMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteStockTagMutationOptions(options), queryClient);
    }

/**
 * Create new transaction with flows.
 * @summary Create
 */
export const createTransaction = (
    transactionData: TransactionData, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TransactionID>> => {


    return axios.default.post(
      `/api/transactions`,
      transactionData,options
    );
  }




export const getCreateTransactionMutationOptions = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTransaction>>, TError,CreateTransactionMutationVariables, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createTransaction>>, TError,CreateTransactionMutationVariables, TContext> => {

const mutationKey = ['createTransaction'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTransaction>>, CreateTransactionMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  createTransaction(data,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateTransactionMutationResult = NonNullable<Awaited<ReturnType<typeof createTransaction>>>
    export type CreateTransactionMutationBody = TransactionData
    export type CreateTransactionMutationError = AxiosError<Error>
    export type CreateTransactionMutationVariables = {data: TransactionData}

    /**
 * @summary Create
 */
export const useCreateTransaction = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTransaction>>, TError,CreateTransactionMutationVariables, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createTransaction>>,
        TError,
        CreateTransactionMutationVariables,
        TContext
      > => {
      return useMutation(getCreateTransactionMutationOptions(options), queryClient);
    }

/**
 * Get a transaction and its flows.
 * @summary Get
 */
export const getTransaction = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TransactionData>> => {


    return axios.default.get(
      `/api/transactions/${id}`,options
    );
  }




export const getGetTransactionQueryKey = (id: string,) => {
    return [
    `/api/transactions/${id}`
    ] as const;
    }


export const getGetTransactionQueryOptions = <TData = Awaited<ReturnType<typeof getTransaction>>, TError = AxiosError<Error>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTransaction>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTransactionQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTransaction>>> = ({ signal }) => getTransaction(id, { signal, ...axiosOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTransaction>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTransactionQueryResult = NonNullable<Awaited<ReturnType<typeof getTransaction>>>
export type GetTransactionQueryError = AxiosError<Error>


export function useGetTransaction<TData = Awaited<ReturnType<typeof getTransaction>>, TError = AxiosError<Error>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTransaction>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTransaction>>,
          TError,
          Awaited<ReturnType<typeof getTransaction>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTransaction<TData = Awaited<ReturnType<typeof getTransaction>>, TError = AxiosError<Error>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTransaction>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTransaction>>,
          TError,
          Awaited<ReturnType<typeof getTransaction>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTransaction<TData = Awaited<ReturnType<typeof getTransaction>>, TError = AxiosError<Error>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTransaction>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get
 */

export function useGetTransaction<TData = Awaited<ReturnType<typeof getTransaction>>, TError = AxiosError<Error>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTransaction>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTransactionQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * Change a transaction and its flows.
 * @summary Update
 */
export const updateTransaction = (
    id: string,
    transactionData: TransactionData, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {


    return axios.default.put(
      `/api/transactions/${id}`,
      transactionData,options
    );
  }




export const getUpdateTransactionMutationOptions = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTransaction>>, TError,UpdateTransactionMutationVariables, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateTransaction>>, TError,UpdateTransactionMutationVariables, TContext> => {

const mutationKey = ['updateTransaction'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTransaction>>, UpdateTransactionMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  updateTransaction(id,data,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateTransactionMutationResult = NonNullable<Awaited<ReturnType<typeof updateTransaction>>>
    export type UpdateTransactionMutationBody = TransactionData
    export type UpdateTransactionMutationError = AxiosError<Error>
    export type UpdateTransactionMutationVariables = {id: string;data: TransactionData}

    /**
 * @summary Update
 */
export const useUpdateTransaction = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTransaction>>, TError,UpdateTransactionMutationVariables, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateTransaction>>,
        TError,
        UpdateTransactionMutationVariables,
        TContext
      > => {
      return useMutation(getUpdateTransactionMutationOptions(options), queryClient);
    }

/**
 * Delete a transaction and its flows.
 * @summary Delete
 */
export const deleteTransaction = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {


    return axios.default.delete(
      `/api/transactions/${id}`,options
    );
  }




export const getDeleteTransactionMutationOptions = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTransaction>>, TError,DeleteTransactionMutationVariables, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteTransaction>>, TError,DeleteTransactionMutationVariables, TContext> => {

const mutationKey = ['deleteTransaction'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTransaction>>, DeleteTransactionMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  deleteTransaction(id,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteTransactionMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTransaction>>>

    export type DeleteTransactionMutationError = AxiosError<Error>
    export type DeleteTransactionMutationVariables = {id: string}

    /**
 * @summary Delete
 */
export const useDeleteTransaction = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTransaction>>, TError,DeleteTransactionMutationVariables, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteTransaction>>,
        TError,
        DeleteTransactionMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteTransactionMutationOptions(options), queryClient);
    }

/**
 * Get all tags.
 * @summary List
 */
export const listTransactionTags = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Tags>> => {


    return axios.default.get(
      `/api/transactions/tags`,options
    );
  }




export const getListTransactionTagsQueryKey = () => {
    return [
    `/api/transactions/tags`
    ] as const;
    }


export const getListTransactionTagsQueryOptions = <TData = Awaited<ReturnType<typeof listTransactionTags>>, TError = AxiosError<Error>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTransactionTags>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListTransactionTagsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listTransactionTags>>> = ({ signal }) => listTransactionTags({ signal, ...axiosOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listTransactionTags>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListTransactionTagsQueryResult = NonNullable<Awaited<ReturnType<typeof listTransactionTags>>>
export type ListTransactionTagsQueryError = AxiosError<Error>


export function useListTransactionTags<TData = Awaited<ReturnType<typeof listTransactionTags>>, TError = AxiosError<Error>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTransactionTags>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTransactionTags>>,
          TError,
          Awaited<ReturnType<typeof listTransactionTags>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTransactionTags<TData = Awaited<ReturnType<typeof listTransactionTags>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTransactionTags>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTransactionTags>>,
          TError,
          Awaited<ReturnType<typeof listTransactionTags>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTransactionTags<TData = Awaited<ReturnType<typeof listTransactionTags>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTransactionTags>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List
 */

export function useListTransactionTags<TData = Awaited<ReturnType<typeof listTransactionTags>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTransactionTags>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListTransactionTagsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * Create a new tag.
 * @summary Create
 */
export const createTransactionTag = (
    tagData: TagData, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TagID>> => {


    return axios.default.post(
      `/api/transactions/tags`,
      tagData,options
    );
  }




export const getCreateTransactionTagMutationOptions = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTransactionTag>>, TError,CreateTransactionTagMutationVariables, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createTransactionTag>>, TError,CreateTransactionTagMutationVariables, TContext> => {

const mutationKey = ['createTransactionTag'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTransactionTag>>, CreateTransactionTagMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  createTransactionTag(data,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateTransactionTagMutationResult = NonNullable<Awaited<ReturnType<typeof createTransactionTag>>>
    export type CreateTransactionTagMutationBody = TagData
    export type CreateTransactionTagMutationError = AxiosError<Error>
    export type CreateTransactionTagMutationVariables = {data: TagData}

    /**
 * @summary Create
 */
export const useCreateTransactionTag = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTransactionTag>>, TError,CreateTransactionTagMutationVariables, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createTransactionTag>>,
        TError,
        CreateTransactionTagMutationVariables,
        TContext
      > => {
      return useMutation(getCreateTransactionTagMutationOptions(options), queryClient);
    }

/**
 * Get a tag.
 * @summary Get
 */
export const getTransactionTag = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TagData>> => {


    return axios.default.get(
      `/api/transactions/tags/${id}`,options
    );
  }




export const getGetTransactionTagQueryKey = (id: string,) => {
    return [
    `/api/transactions/tags/${id}`
    ] as const;
    }


export const getGetTransactionTagQueryOptions = <TData = Awaited<ReturnType<typeof getTransactionTag>>, TError = AxiosError<Error>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTransactionTag>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTransactionTagQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTransactionTag>>> = ({ signal }) => getTransactionTag(id, { signal, ...axiosOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTransactionTag>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTransactionTagQueryResult = NonNullable<Awaited<ReturnType<typeof getTransactionTag>>>
export type GetTransactionTagQueryError = AxiosError<Error>


export function useGetTransactionTag<TData = Awaited<ReturnType<typeof getTransactionTag>>, TError = AxiosError<Error>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTransactionTag>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTransactionTag>>,
          TError,
          Awaited<ReturnType<typeof getTransactionTag>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTransactionTag<TData = Awaited<ReturnType<typeof getTransactionTag>>, TError = AxiosError<Error>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTransactionTag>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTransactionTag>>,
          TError,
          Awaited<ReturnType<typeof getTransactionTag>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTransactionTag<TData = Awaited<ReturnType<typeof getTransactionTag>>, TError = AxiosError<Error>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTransactionTag>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get
 */

export function useGetTransactionTag<TData = Awaited<ReturnType<typeof getTransactionTag>>, TError = AxiosError<Error>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTransactionTag>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTransactionTagQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * Change a tag.
 * @summary Update
 */
export const updateTransactionTag = (
    id: string,
    tagData: TagData, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {


    return axios.default.put(
      `/api/transactions/tags/${id}`,
      tagData,options
    );
  }




export const getUpdateTransactionTagMutationOptions = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTransactionTag>>, TError,UpdateTransactionTagMutationVariables, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateTransactionTag>>, TError,UpdateTransactionTagMutationVariables, TContext> => {

const mutationKey = ['updateTransactionTag'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTransactionTag>>, UpdateTransactionTagMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  updateTransactionTag(id,data,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateTransactionTagMutationResult = NonNullable<Awaited<ReturnType<typeof updateTransactionTag>>>
    export type UpdateTransactionTagMutationBody = TagData
    export type UpdateTransactionTagMutationError = AxiosError<Error>
    export type UpdateTransactionTagMutationVariables = {id: string;data: TagData}

    /**
 * @summary Update
 */
export const useUpdateTransactionTag = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTransactionTag>>, TError,UpdateTransactionTagMutationVariables, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateTransactionTag>>,
        TError,
        UpdateTransactionTagMutationVariables,
        TContext
      > => {
      return useMutation(getUpdateTransactionTagMutationOptions(options), queryClient);
    }

/**
 * Delete a tag.
 * @summary Delete
 */
export const deleteTransactionTag = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {


    return axios.default.delete(
      `/api/transactions/tags/${id}`,options
    );
  }




export const getDeleteTransactionTagMutationOptions = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTransactionTag>>, TError,DeleteTransactionTagMutationVariables, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteTransactionTag>>, TError,DeleteTransactionTagMutationVariables, TContext> => {

const mutationKey = ['deleteTransactionTag'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTransactionTag>>, DeleteTransactionTagMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  deleteTransactionTag(id,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteTransactionTagMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTransactionTag>>>

    export type DeleteTransactionTagMutationError = AxiosError<Error>
    export type DeleteTransactionTagMutationVariables = {id: string}

    /**
 * @summary Delete
 */
export const useDeleteTransactionTag = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTransactionTag>>, TError,DeleteTransactionTagMutationVariables, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteTransactionTag>>,
        TError,
        DeleteTransactionTagMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteTransactionTagMutationOptions(options), queryClient);
    }

/**
 * Get all tags.
 * @summary List
 */
export const listFlowTags = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Tags>> => {


    return axios.default.get(
      `/api/flows/tags`,options
    );
  }




export const getListFlowTagsQueryKey = () => {
    return [
    `/api/flows/tags`
    ] as const;
    }


export const getListFlowTagsQueryOptions = <TData = Awaited<ReturnType<typeof listFlowTags>>, TError = AxiosError<Error>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlowTags>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListFlowTagsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listFlowTags>>> = ({ signal }) => listFlowTags({ signal, ...axiosOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listFlowTags>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListFlowTagsQueryResult = NonNullable<Awaited<ReturnType<typeof listFlowTags>>>
export type ListFlowTagsQueryError = AxiosError<Error>


export function useListFlowTags<TData = Awaited<ReturnType<typeof listFlowTags>>, TError = AxiosError<Error>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlowTags>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFlowTags>>,
          TError,
          Awaited<ReturnType<typeof listFlowTags>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFlowTags<TData = Awaited<ReturnType<typeof listFlowTags>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlowTags>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFlowTags>>,
          TError,
          Awaited<ReturnType<typeof listFlowTags>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFlowTags<TData = Awaited<ReturnType<typeof listFlowTags>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlowTags>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List
 */

export function useListFlowTags<TData = Awaited<ReturnType<typeof listFlowTags>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFlowTags>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListFlowTagsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * Create a new tag.
 * @summary Create
 */
export const createFlowTag = (
    tagData: TagData, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TagID>> => {


    return axios.default.post(
      `/api/flows/tags`,
      tagData,options
    );
  }




export const getCreateFlowTagMutationOptions = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createFlowTag>>, TError,CreateFlowTagMutationVariables, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createFlowTag>>, TError,CreateFlowTagMutationVariables, TContext> => {

const mutationKey = ['createFlowTag'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createFlowTag>>, CreateFlowTagMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  createFlowTag(data,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateFlowTagMutationResult = NonNullable<Awaited<ReturnType<typeof createFlowTag>>>
    export type CreateFlowTagMutationBody = TagData
    export type CreateFlowTagMutationError = AxiosError<Error>
    export type CreateFlowTagMutationVariables = {data: TagData}

    /**
 * @summary Create
 */
export const useCreateFlowTag = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createFlowTag>>, TError,CreateFlowTagMutationVariables, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createFlowTag>>,
        TError,
        CreateFlowTagMutationVariables,
        TContext
      > => {
      return useMutation(getCreateFlowTagMutationOptions(options), queryClient);
    }

/**
 * Get a tag.
 * @summary Get
 */
export const getFlowTag = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TagData>> => {


    return axios.default.get(
      `/api/flows/tags/${id}`,options
    );
  }




export const getGetFlowTagQueryKey = (id: string,) => {
    return [
    `/api/flows/tags/${id}`
    ] as const;
    }


export const getGetFlowTagQueryOptions = <TData = Awaited<ReturnType<typeof getFlowTag>>, TError = AxiosError<Error>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlowTag>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFlowTagQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFlowTag>>> = ({ signal }) => getFlowTag(id, { signal, ...axiosOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFlowTag>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFlowTagQueryResult = NonNullable<Awaited<ReturnType<typeof getFlowTag>>>
export type GetFlowTagQueryError = AxiosError<Error>


export function useGetFlowTag<TData = Awaited<ReturnType<typeof getFlowTag>>, TError = AxiosError<Error>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlowTag>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFlowTag>>,
          TError,
          Awaited<ReturnType<typeof getFlowTag>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFlowTag<TData = Awaited<ReturnType<typeof getFlowTag>>, TError = AxiosError<Error>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlowTag>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFlowTag>>,
          TError,
          Awaited<ReturnType<typeof getFlowTag>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFlowTag<TData = Awaited<ReturnType<typeof getFlowTag>>, TError = AxiosError<Error>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlowTag>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get
 */

export function useGetFlowTag<TData = Awaited<ReturnType<typeof getFlowTag>>, TError = AxiosError<Error>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlowTag>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFlowTagQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * Change a tag.
 * @summary Update
 */
export const updateFlowTag = (
    id: string,
    tagData: TagData, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {


    return axios.default.put(
      `/api/flows/tags/${id}`,
      tagData,options
    );
  }




export const getUpdateFlowTagMutationOptions = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateFlowTag>>, TError,UpdateFlowTagMutationVariables, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateFlowTag>>, TError,UpdateFlowTagMutationVariables, TContext> => {

const mutationKey = ['updateFlowTag'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateFlowTag>>, UpdateFlowTagMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  updateFlowTag(id,data,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateFlowTagMutationResult = NonNullable<Awaited<ReturnType<typeof updateFlowTag>>>
    export type UpdateFlowTagMutationBody = TagData
    export type UpdateFlowTagMutationError = AxiosError<Error>
    export type UpdateFlowTagMutationVariables = {id: string;data: TagData}

    /**
 * @summary Update
 */
export const useUpdateFlowTag = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateFlowTag>>, TError,UpdateFlowTagMutationVariables, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateFlowTag>>,
        TError,
        UpdateFlowTagMutationVariables,
        TContext
      > => {
      return useMutation(getUpdateFlowTagMutationOptions(options), queryClient);
    }

/**
 * Delete a tag.
 * @summary Delete
 */
export const deleteFlowTag = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {


    return axios.default.delete(
      `/api/flows/tags/${id}`,options
    );
  }




export const getDeleteFlowTagMutationOptions = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteFlowTag>>, TError,DeleteFlowTagMutationVariables, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteFlowTag>>, TError,DeleteFlowTagMutationVariables, TContext> => {

const mutationKey = ['deleteFlowTag'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteFlowTag>>, DeleteFlowTagMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  deleteFlowTag(id,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteFlowTagMutationResult = NonNullable<Awaited<ReturnType<typeof deleteFlowTag>>>

    export type DeleteFlowTagMutationError = AxiosError<Error>
    export type DeleteFlowTagMutationVariables = {id: string}

    /**
 * @summary Delete
 */
export const useDeleteFlowTag = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteFlowTag>>, TError,DeleteFlowTagMutationVariables, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteFlowTag>>,
        TError,
        DeleteFlowTagMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteFlowTagMutationOptions(options), queryClient);
    }
