openapi: 3.1.0
info:
  title: FSLedger
  version: 0.0.1
  description: A highly customizable personal ledger based on the Flow & Stock model.
  contact:
    url: https://github.com/M-Haruki/fsledger
  license:
    name: GNU Affero General Public License v3.0
    url: https://github.com/M-Haruki/fsledger/blob/main/LICENSE
servers:
  - url: http://localhost:1323/api
    description: develop environment
tags:
  - name: stock
    description: stock
  - name: transaction
    description: transaction
  - name: flow
    description: flow
  - name: tag
    description: tag
  - name: common
    description: common
paths:
  /health:
    $ref: "./paths/common.yml#/Health"
  /stocks:
    $ref: "paths/stocks.yml#/Stocks"
  /stocks/{id}:
    $ref: "paths/stocks.yml#/StocksID"
  # /transactions:
  #   $ref: "paths/transactions.yml#/Transactions"
  # /transactions/{id}:
  #   $ref: "paths/transactions.yml#/TransactionsID"
  # /transactions/{id}/flow:
  #   $ref: "paths/flows.yml#/Flows"
  # /flows/{id}:
  #   $ref: "paths/flows.yml#/FlowsID"
  # /{type}/tags:
  #   $ref: "paths/tags.yml#/Tags_"
  # /{type}/tags/{id}:
  #   $ref: "paths/tags.yml#/TagsID"
