/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FSLedger
 * A highly customizable personal ledger based on the Flow & Stock model.
 * OpenAPI spec version: 0.0.1
 */

export interface TagData {
  /** @minLength 1 */
  name: string;
}
