// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: common.sql

package sqlc

import (
	"context"
)

const check = `-- name: Check :exec
SELECT 1
`

func (q *Queries) Check(ctx context.Context) error {
	_, err := q.db.Exec(ctx, check)
	return err
}
