// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: flow.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFlow = `-- name: CreateFlow :one
INSERT INTO flows (transaction_id, from_stock_id, to_stock_id, amount) VALUES ($1, $2, $3, $4) RETURNING id
`

type CreateFlowParams struct {
	Transactionid pgtype.UUID
	Fromstockid   pgtype.UUID
	Tostockid     pgtype.UUID
	Amount        int64
}

func (q *Queries) CreateFlow(ctx context.Context, arg CreateFlowParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createFlow,
		arg.Transactionid,
		arg.Fromstockid,
		arg.Tostockid,
		arg.Amount,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createFlowTag = `-- name: CreateFlowTag :one
INSERT INTO flow_tags (name) VALUES ($1) RETURNING id
`

func (q *Queries) CreateFlowTag(ctx context.Context, name string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createFlowTag, name)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteFlow = `-- name: DeleteFlow :exec
DELETE FROM flows WHERE id = $1
`

func (q *Queries) DeleteFlow(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFlow, id)
	return err
}

const deleteFlowTag = `-- name: DeleteFlowTag :execresult
DELETE FROM flow_tags WHERE id = $1
`

func (q *Queries) DeleteFlowTag(ctx context.Context, id pgtype.UUID) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteFlowTag, id)
}

const getFlowTag = `-- name: GetFlowTag :one
SELECT name FROM flow_tags WHERE id = $1
`

func (q *Queries) GetFlowTag(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getFlowTag, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const listFlowByTransaction = `-- name: ListFlowByTransaction :many
SELECT id, from_stock_id, to_stock_id, amount FROM flows WHERE transaction_id = $1
`

type ListFlowByTransactionRow struct {
	ID          pgtype.UUID
	FromStockID pgtype.UUID
	ToStockID   pgtype.UUID
	Amount      int64
}

func (q *Queries) ListFlowByTransaction(ctx context.Context, id pgtype.UUID) ([]ListFlowByTransactionRow, error) {
	rows, err := q.db.Query(ctx, listFlowByTransaction, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFlowByTransactionRow
	for rows.Next() {
		var i ListFlowByTransactionRow
		if err := rows.Scan(
			&i.ID,
			&i.FromStockID,
			&i.ToStockID,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlowTags = `-- name: ListFlowTags :many
SELECT id, name FROM flow_tags
`

func (q *Queries) ListFlowTags(ctx context.Context) ([]FlowTag, error) {
	rows, err := q.db.Query(ctx, listFlowTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlowTag
	for rows.Next() {
		var i FlowTag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFlow = `-- name: UpdateFlow :exec
UPDATE flows SET from_stock_id = $1, to_stock_id = $2, amount = $3 WHERE id = $4
`

type UpdateFlowParams struct {
	Fromstockid pgtype.UUID
	Tostockid   pgtype.UUID
	Amount      int64
	ID          pgtype.UUID
}

func (q *Queries) UpdateFlow(ctx context.Context, arg UpdateFlowParams) error {
	_, err := q.db.Exec(ctx, updateFlow,
		arg.Fromstockid,
		arg.Tostockid,
		arg.Amount,
		arg.ID,
	)
	return err
}

const updateFlowTag = `-- name: UpdateFlowTag :execresult
UPDATE flow_tags SET name = $1 WHERE id = $2
`

type UpdateFlowTagParams struct {
	Name string
	ID   pgtype.UUID
}

func (q *Queries) UpdateFlowTag(ctx context.Context, arg UpdateFlowTagParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateFlowTag, arg.Name, arg.ID)
}
