// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Flow struct {
	ID            pgtype.UUID
	TransactionID pgtype.UUID
	FromStockID   pgtype.UUID
	ToStockID     pgtype.UUID
	Amount        int64
}

type FlowTag struct {
	ID   pgtype.UUID
	Name string
}

type FlowTagRelation struct {
	FlowID pgtype.UUID
	TagID  pgtype.UUID
}

type Stock struct {
	ID   pgtype.UUID
	Name string
	// Whether the total amount is meaningful
	HasAmount        bool
	Currency         string
	CurrencyExponent int32
	Description      string
}

type StockTag struct {
	ID   pgtype.UUID
	Name string
}

type StockTagRelation struct {
	StockID pgtype.UUID
	TagID   pgtype.UUID
}

type Transaction struct {
	ID          pgtype.UUID
	Description string
	OccurredAt  pgtype.Date
}

type TransactionTag struct {
	ID   pgtype.UUID
	Name string
}

type TransactionTagRelation struct {
	TransactionID pgtype.UUID
	TagID         pgtype.UUID
}
