// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	Check(ctx context.Context) error
	CreateFlow(ctx context.Context, arg CreateFlowParams) (pgtype.UUID, error)
	CreateFlowTag(ctx context.Context, name string) (pgtype.UUID, error)
	CreateStock(ctx context.Context, arg CreateStockParams) (pgtype.UUID, error)
	CreateStockTag(ctx context.Context, name string) (pgtype.UUID, error)
	CreateStockTagRelation(ctx context.Context, arg CreateStockTagRelationParams) error
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (pgtype.UUID, error)
	CreateTransactionTag(ctx context.Context, name string) (pgtype.UUID, error)
	DeleteFlow(ctx context.Context, id pgtype.UUID) error
	DeleteFlowTag(ctx context.Context, id pgtype.UUID) (pgconn.CommandTag, error)
	DeleteStock(ctx context.Context, id pgtype.UUID) (pgconn.CommandTag, error)
	DeleteStockTag(ctx context.Context, id pgtype.UUID) (pgconn.CommandTag, error)
	DeleteStockTagRelation(ctx context.Context, stockID pgtype.UUID) error
	DeleteTransaction(ctx context.Context, id pgtype.UUID) error
	DeleteTransactionTag(ctx context.Context, id pgtype.UUID) (pgconn.CommandTag, error)
	GetFlowTag(ctx context.Context, id pgtype.UUID) (string, error)
	GetStock(ctx context.Context, id pgtype.UUID) (GetStockRow, error)
	GetStockTag(ctx context.Context, id pgtype.UUID) (string, error)
	GetTransaction(ctx context.Context, id pgtype.UUID) (GetTransactionRow, error)
	GetTransactionTag(ctx context.Context, id pgtype.UUID) (string, error)
	ListFlowByTransaction(ctx context.Context, id pgtype.UUID) ([]ListFlowByTransactionRow, error)
	ListFlowTags(ctx context.Context) ([]FlowTag, error)
	ListStockTags(ctx context.Context) ([]StockTag, error)
	ListStocks(ctx context.Context) ([]ListStocksRow, error)
	ListTagIDsByStock(ctx context.Context, id pgtype.UUID) ([]pgtype.UUID, error)
	ListTagsByTransaction(ctx context.Context, id pgtype.UUID) ([]ListTagsByTransactionRow, error)
	ListTransactionTags(ctx context.Context) ([]TransactionTag, error)
	UpdateFlow(ctx context.Context, arg UpdateFlowParams) error
	UpdateFlowTag(ctx context.Context, arg UpdateFlowTagParams) (pgconn.CommandTag, error)
	UpdateStock(ctx context.Context, arg UpdateStockParams) (pgconn.CommandTag, error)
	UpdateStockTag(ctx context.Context, arg UpdateStockTagParams) (pgconn.CommandTag, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) error
	UpdateTransactionTag(ctx context.Context, arg UpdateTransactionTagParams) (pgconn.CommandTag, error)
}

var _ Querier = (*Queries)(nil)
