// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stock.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createStock = `-- name: CreateStock :one
INSERT INTO stocks (name, has_amount, currency, description) VALUES ($1, $2, $3, $4) RETURNING id
`

type CreateStockParams struct {
	Name        string
	Hasamount   bool
	Currency    string
	Description string
}

func (q *Queries) CreateStock(ctx context.Context, arg CreateStockParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createStock,
		arg.Name,
		arg.Hasamount,
		arg.Currency,
		arg.Description,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createStockTag = `-- name: CreateStockTag :one
INSERT INTO stock_tags (name) VALUES ($1) RETURNING id
`

func (q *Queries) CreateStockTag(ctx context.Context, name string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createStockTag, name)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createStockTagRelation = `-- name: CreateStockTagRelation :exec
INSERT INTO stock_tag_relations (stock_id, tag_id) VALUES ($1, $2)
`

type CreateStockTagRelationParams struct {
	StockID pgtype.UUID
	TagID   pgtype.UUID
}

func (q *Queries) CreateStockTagRelation(ctx context.Context, arg CreateStockTagRelationParams) error {
	_, err := q.db.Exec(ctx, createStockTagRelation, arg.StockID, arg.TagID)
	return err
}

const deleteStock = `-- name: DeleteStock :execresult
DELETE FROM stocks WHERE id = $1
`

func (q *Queries) DeleteStock(ctx context.Context, id pgtype.UUID) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteStock, id)
}

const deleteStockTag = `-- name: DeleteStockTag :exec
DELETE FROM stock_tags WHERE id = $1
`

func (q *Queries) DeleteStockTag(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteStockTag, id)
	return err
}

const deleteStockTagRelation = `-- name: DeleteStockTagRelation :exec
DELETE FROM stock_tag_relations WHERE stock_id = $1 AND tag_id = $2
`

type DeleteStockTagRelationParams struct {
	StockID pgtype.UUID
	TagID   pgtype.UUID
}

func (q *Queries) DeleteStockTagRelation(ctx context.Context, arg DeleteStockTagRelationParams) error {
	_, err := q.db.Exec(ctx, deleteStockTagRelation, arg.StockID, arg.TagID)
	return err
}

const getStock = `-- name: GetStock :one
SELECT id, name, has_amount, currency, description FROM stocks WHERE id = $1
`

func (q *Queries) GetStock(ctx context.Context, id pgtype.UUID) (Stock, error) {
	row := q.db.QueryRow(ctx, getStock, id)
	var i Stock
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HasAmount,
		&i.Currency,
		&i.Description,
	)
	return i, err
}

const getStockTag = `-- name: GetStockTag :one
SELECT id, name FROM stock_tags WHERE id = $1
`

func (q *Queries) GetStockTag(ctx context.Context, id pgtype.UUID) (StockTag, error) {
	row := q.db.QueryRow(ctx, getStockTag, id)
	var i StockTag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listStockTags = `-- name: ListStockTags :many
SELECT id, name FROM stock_tags
`

func (q *Queries) ListStockTags(ctx context.Context) ([]StockTag, error) {
	rows, err := q.db.Query(ctx, listStockTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockTag
	for rows.Next() {
		var i StockTag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStocks = `-- name: ListStocks :many
SELECT id, name FROM stocks
`

type ListStocksRow struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) ListStocks(ctx context.Context) ([]ListStocksRow, error) {
	rows, err := q.db.Query(ctx, listStocks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStocksRow
	for rows.Next() {
		var i ListStocksRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByStock = `-- name: ListTagsByStock :many
SELECT r.tag_id AS id, t.name AS name FROM stock_tag_relations r JOIN stock_tags t ON r.tag_id = t.id WHERE r.stock_id = $1
`

type ListTagsByStockRow struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) ListTagsByStock(ctx context.Context, id pgtype.UUID) ([]ListTagsByStockRow, error) {
	rows, err := q.db.Query(ctx, listTagsByStock, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsByStockRow
	for rows.Next() {
		var i ListTagsByStockRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStock = `-- name: UpdateStock :exec
UPDATE stocks SET name = $1, has_amount = $2, currency = $3, description = $4 WHERE id = $5
`

type UpdateStockParams struct {
	Name        string
	Hasamount   bool
	Currency    string
	Description string
	ID          pgtype.UUID
}

func (q *Queries) UpdateStock(ctx context.Context, arg UpdateStockParams) error {
	_, err := q.db.Exec(ctx, updateStock,
		arg.Name,
		arg.Hasamount,
		arg.Currency,
		arg.Description,
		arg.ID,
	)
	return err
}

const updateStockTag = `-- name: UpdateStockTag :exec
UPDATE stock_tags SET name = $1 WHERE id = $2
`

type UpdateStockTagParams struct {
	Name string
	ID   pgtype.UUID
}

func (q *Queries) UpdateStockTag(ctx context.Context, arg UpdateStockTagParams) error {
	_, err := q.db.Exec(ctx, updateStockTag, arg.Name, arg.ID)
	return err
}
