// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transaction.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (description, occurred_at) VALUES ($1, $2) RETURNING id
`

type CreateTransactionParams struct {
	Description string
	Occurredat  pgtype.Date
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createTransaction, arg.Description, arg.Occurredat)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createTransactionTag = `-- name: CreateTransactionTag :one
INSERT INTO transaction_tags (name) VALUES ($1) RETURNING id
`

func (q *Queries) CreateTransactionTag(ctx context.Context, name string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createTransactionTag, name)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions WHERE id = $1
`

func (q *Queries) DeleteTransaction(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTransaction, id)
	return err
}

const deleteTransactionTag = `-- name: DeleteTransactionTag :execresult
DELETE FROM transaction_tags WHERE id = $1
`

func (q *Queries) DeleteTransactionTag(ctx context.Context, id pgtype.UUID) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteTransactionTag, id)
}

const getTransaction = `-- name: GetTransaction :one
SELECT description, occurred_at FROM transactions WHERE id = $1
`

type GetTransactionRow struct {
	Description string
	OccurredAt  pgtype.Date
}

func (q *Queries) GetTransaction(ctx context.Context, id pgtype.UUID) (GetTransactionRow, error) {
	row := q.db.QueryRow(ctx, getTransaction, id)
	var i GetTransactionRow
	err := row.Scan(&i.Description, &i.OccurredAt)
	return i, err
}

const getTransactionTag = `-- name: GetTransactionTag :one
SELECT name FROM transaction_tags WHERE id = $1
`

func (q *Queries) GetTransactionTag(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getTransactionTag, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const listTagsByTransaction = `-- name: ListTagsByTransaction :many
SELECT r.tag_id AS id, t.name AS name FROM transaction_tag_relations r JOIN transaction_tags t ON r.tag_id = t.id WHERE r.transaction_id = $1
`

type ListTagsByTransactionRow struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) ListTagsByTransaction(ctx context.Context, id pgtype.UUID) ([]ListTagsByTransactionRow, error) {
	rows, err := q.db.Query(ctx, listTagsByTransaction, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsByTransactionRow
	for rows.Next() {
		var i ListTagsByTransactionRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionTags = `-- name: ListTransactionTags :many
SELECT id, name FROM transaction_tags
`

func (q *Queries) ListTransactionTags(ctx context.Context) ([]TransactionTag, error) {
	rows, err := q.db.Query(ctx, listTransactionTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransactionTag
	for rows.Next() {
		var i TransactionTag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :exec
UPDATE transactions SET description = $1, occurred_at = $2 WHERE id = $3
`

type UpdateTransactionParams struct {
	Description string
	Occurredat  pgtype.Date
	ID          pgtype.UUID
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) error {
	_, err := q.db.Exec(ctx, updateTransaction, arg.Description, arg.Occurredat, arg.ID)
	return err
}

const updateTransactionTag = `-- name: UpdateTransactionTag :execresult
UPDATE transaction_tags SET name = $1 WHERE id = $2
`

type UpdateTransactionTagParams struct {
	Name string
	ID   pgtype.UUID
}

func (q *Queries) UpdateTransactionTag(ctx context.Context, arg UpdateTransactionTagParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateTransactionTag, arg.Name, arg.ID)
}
