/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FSLedger
 * A highly customizable personal ledger based on the Flow & Stock model.
 * OpenAPI spec version: 0.0.1
 */
import type { StockData } from './stockData';

export type StocksViewItem = {
  id: string;
  total: number;
} & StockData;
