/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FSLedger
 * A highly customizable personal ledger based on the Flow & Stock model.
 * OpenAPI spec version: 0.0.1
 */

export type StocksItem = {
  id: string;
  /** @minLength 1 */
  name: string;
  hasAmount: boolean;
  currency: string;
  currencyExponent: number;
};
