/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FSLedger
 * A highly customizable personal ledger based on the Flow & Stock model.
 * OpenAPI spec version: 0.0.1
 */
import type { TagData } from './tagData';
import type { TagID } from './tagID';

export type Tags = (TagID & TagData)[];
