/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FSLedger
 * A highly customizable personal ledger based on the Flow & Stock model.
 * OpenAPI spec version: 0.0.1
 */
import type { FlowData } from './flowData';

export interface TransactionData {
  description: string;
  occurred_at: string;
  tags: string[];
  flows: FlowData[];
}
