/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FSLedger
 * A highly customizable personal ledger based on the Flow & Stock model.
 * OpenAPI spec version: 0.0.1
 */
import type { TransactionData } from './transactionData';

export type TransactionsViewItem = {
  id: string;
} & TransactionData;
