/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FSLedger
 * A highly customizable personal ledger based on the Flow & Stock model.
 * OpenAPI spec version: 0.0.1
 */
import type { ViewDSLRuleForFlowView } from './viewDSLRuleForFlowView';

export type ViewDSLLogicForFlowView = {
  AND: ViewDSLRuleForFlowView[];
} | {
  OR: ViewDSLRuleForFlowView[];
} | {
  NOT: ViewDSLRuleForFlowView;
};
