/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FSLedger
 * A highly customizable personal ledger based on the Flow & Stock model.
 * OpenAPI spec version: 0.0.1
 */

export type ViewDSLFlowCondition = {
  target: 'flows';
  tags: string[];
} | (unknown & {
  target: 'flows';
  'amount-min'?: number;
  'amount-max'?: number;
});
