/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FSLedger
 * A highly customizable personal ledger based on the Flow & Stock model.
 * OpenAPI spec version: 0.0.1
 */
import type { ViewDSLFlowCondition } from './viewDSLFlowCondition';
import type { ViewDSLLogicForFlowView } from './viewDSLLogicForFlowView';
import type { ViewDSLStockConditionForFlowView } from './viewDSLStockConditionForFlowView';
import type { ViewDSLTransactionCondition } from './viewDSLTransactionCondition';

export type ViewDSLRuleForFlowView = ViewDSLLogicForFlowView | ViewDSLStockConditionForFlowView | ViewDSLTransactionCondition | ViewDSLFlowCondition;
