/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FSLedger
 * A highly customizable personal ledger based on the Flow & Stock model.
 * OpenAPI spec version: 0.0.1
 */

export type ViewDSLTransactionCondition = {
  target: 'transactions';
  tags: string[];
} | {
  target: 'transactions';
  mode: 'absolute';
  relation: 'before' | 'before-or-equal' | 'point' | 'after-or-equal' | 'after';
  unit: 'day' | 'month' | 'year';
  num: number;
} | {
  target: 'transactions';
  mode: 'absolute';
  relation: 'before' | 'before-or-equal' | 'point' | 'after-or-equal' | 'after';
  unit: 'year-month' | 'year-month-day';
  date: string;
} | {
  target: 'transactions';
  mode: 'relative';
  relation: 'before' | 'before-or-equal' | 'point' | 'after-or-equal' | 'after';
  unit: 'day' | 'month' | 'year';
  num: number;
};
