/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FSLedger
 * A highly customizable personal ledger based on the Flow & Stock model.
 * OpenAPI spec version: 0.0.1
 */
import type { ViewDSLRuleForTransactionView } from './viewDSLRuleForTransactionView';

export type ViewDSLLogicForTransactionView = {
  AND: ViewDSLRuleForTransactionView[];
} | {
  OR: ViewDSLRuleForTransactionView[];
} | {
  NOT: ViewDSLRuleForTransactionView;
};
