// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// StockData defines model for StockData.
type StockData struct {
	Currency         string               `json:"currency"`
	CurrencyExponent int32                `json:"currencyExponent"`
	Description      string               `json:"description"`
	HasAmount        bool                 `json:"hasAmount"`
	Name             string               `json:"name"`
	Tags             []openapi_types.UUID `json:"tags"`
}

// StockID defines model for StockID.
type StockID struct {
	Id openapi_types.UUID `json:"id"`
}

// Stocks defines model for Stocks.
type Stocks = []struct {
	Currency         string             `json:"currency"`
	CurrencyExponent int32              `json:"currencyExponent"`
	HasAmount        bool               `json:"hasAmount"`
	Id               openapi_types.UUID `json:"id"`
	Name             string             `json:"name"`
}

// TagData defines model for TagData.
type TagData struct {
	Name string `json:"name"`
}

// TagID defines model for TagID.
type TagID struct {
	Id openapi_types.UUID `json:"id"`
}

// Tags defines model for Tags.
type Tags = []struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
}

// StockIDParam defines model for StockIDParam.
type StockIDParam = openapi_types.UUID

// TagIDParam defines model for TagIDParam.
type TagIDParam = openapi_types.UUID

// CreateStockJSONRequestBody defines body for CreateStock for application/json ContentType.
type CreateStockJSONRequestBody = StockData

// CreateStockTagsJSONRequestBody defines body for CreateStockTags for application/json ContentType.
type CreateStockTagsJSONRequestBody = TagData

// UpdateStockTagJSONRequestBody defines body for UpdateStockTag for application/json ContentType.
type UpdateStockTagJSONRequestBody = TagData

// UpdateStockJSONRequestBody defines body for UpdateStock for application/json ContentType.
type UpdateStockJSONRequestBody = StockData

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// HealthCheck Health Check
	// (GET /health)
	HealthCheck(ctx *echo.Context) error
	// ListStocks List
	// (GET /stocks)
	ListStocks(ctx *echo.Context) error
	// CreateStock Create
	// (POST /stocks)
	CreateStock(ctx *echo.Context) error
	// ListStockTags List
	// (GET /stocks/tags)
	ListStockTags(ctx *echo.Context) error
	// CreateStockTags Create
	// (POST /stocks/tags)
	CreateStockTags(ctx *echo.Context) error
	// DeleteStockTag Delete
	// (DELETE /stocks/tags/{id})
	DeleteStockTag(ctx *echo.Context, id TagIDParam) error
	// GetStockTag Get
	// (GET /stocks/tags/{id})
	GetStockTag(ctx *echo.Context, id TagIDParam) error
	// UpdateStockTag Update
	// (PUT /stocks/tags/{id})
	UpdateStockTag(ctx *echo.Context, id TagIDParam) error
	// DeleteStock Delete
	// (DELETE /stocks/{id})
	DeleteStock(ctx *echo.Context, id StockIDParam) error
	// GetStock Get
	// (GET /stocks/{id})
	GetStock(ctx *echo.Context, id StockIDParam) error
	// UpdateStock Update
	// (PUT /stocks/{id})
	UpdateStock(ctx *echo.Context, id StockIDParam) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// HealthCheck converts echo context to params.
func (w *ServerInterfaceWrapper) HealthCheck(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.HealthCheck(ctx)
	return err
}

// ListStocks converts echo context to params.
func (w *ServerInterfaceWrapper) ListStocks(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListStocks(ctx)
	return err
}

// CreateStock converts echo context to params.
func (w *ServerInterfaceWrapper) CreateStock(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateStock(ctx)
	return err
}

// ListStockTags converts echo context to params.
func (w *ServerInterfaceWrapper) ListStockTags(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListStockTags(ctx)
	return err
}

// CreateStockTags converts echo context to params.
func (w *ServerInterfaceWrapper) CreateStockTags(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateStockTags(ctx)
	return err
}

// DeleteStockTag converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteStockTag(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id TagIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteStockTag(ctx, id)
	return err
}

// GetStockTag converts echo context to params.
func (w *ServerInterfaceWrapper) GetStockTag(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id TagIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetStockTag(ctx, id)
	return err
}

// UpdateStockTag converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateStockTag(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id TagIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateStockTag(ctx, id)
	return err
}

// DeleteStock converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteStock(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id StockIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteStock(ctx, id)
	return err
}

// GetStock converts echo context to params.
func (w *ServerInterfaceWrapper) GetStock(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id StockIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetStock(ctx, id)
	return err
}

// UpdateStock converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateStock(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id StockIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateStock(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/health", wrapper.HealthCheck, options.OperationMiddlewares["healthCheck"]...)
	router.GET(options.BaseURL+"/stocks", wrapper.ListStocks, options.OperationMiddlewares["listStocks"]...)
	router.POST(options.BaseURL+"/stocks", wrapper.CreateStock, options.OperationMiddlewares["createStock"]...)
	router.DELETE(options.BaseURL+"/stocks/:id", wrapper.DeleteStock, options.OperationMiddlewares["deleteStock"]...)
	router.GET(options.BaseURL+"/stocks/:id", wrapper.GetStock, options.OperationMiddlewares["getStock"]...)
	router.PUT(options.BaseURL+"/stocks/:id", wrapper.UpdateStock, options.OperationMiddlewares["updateStock"]...)
	router.GET(options.BaseURL+"/stocks/tags", wrapper.ListStockTags, options.OperationMiddlewares["listStockTags"]...)
	router.POST(options.BaseURL+"/stocks/tags", wrapper.CreateStockTags, options.OperationMiddlewares["createStockTags"]...)
	router.DELETE(options.BaseURL+"/stocks/tags/:id", wrapper.DeleteStockTag, options.OperationMiddlewares["deleteStockTag"]...)
	router.GET(options.BaseURL+"/stocks/tags/:id", wrapper.GetStockTag, options.OperationMiddlewares["getStockTag"]...)
	router.PUT(options.BaseURL+"/stocks/tags/:id", wrapper.UpdateStockTag, options.OperationMiddlewares["updateStockTag"]...)

}

type HealthCheckRequestObject struct {
}

type HealthCheckResponseObject interface {
	VisitHealthCheckResponse(w http.ResponseWriter) error
}

type HealthCheck204Response struct {
}

func (response HealthCheck204Response) VisitHealthCheckResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type HealthCheck503JSONResponse Error

func (response HealthCheck503JSONResponse) VisitHealthCheckResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type ListStocksRequestObject struct {
}

type ListStocksResponseObject interface {
	VisitListStocksResponse(w http.ResponseWriter) error
}

type ListStocks200JSONResponse Stocks

func (response ListStocks200JSONResponse) VisitListStocksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListStocks500JSONResponse Error

func (response ListStocks500JSONResponse) VisitListStocksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateStockRequestObject struct {
	Body *CreateStockJSONRequestBody
}

type CreateStockResponseObject interface {
	VisitCreateStockResponse(w http.ResponseWriter) error
}

type CreateStock201JSONResponse StockID

func (response CreateStock201JSONResponse) VisitCreateStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateStock400JSONResponse Error

func (response CreateStock400JSONResponse) VisitCreateStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateStock500JSONResponse Error

func (response CreateStock500JSONResponse) VisitCreateStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListStockTagsRequestObject struct {
}

type ListStockTagsResponseObject interface {
	VisitListStockTagsResponse(w http.ResponseWriter) error
}

type ListStockTags200JSONResponse Tags

func (response ListStockTags200JSONResponse) VisitListStockTagsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListStockTags400JSONResponse Error

func (response ListStockTags400JSONResponse) VisitListStockTagsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListStockTags500JSONResponse Error

func (response ListStockTags500JSONResponse) VisitListStockTagsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateStockTagsRequestObject struct {
	Body *CreateStockTagsJSONRequestBody
}

type CreateStockTagsResponseObject interface {
	VisitCreateStockTagsResponse(w http.ResponseWriter) error
}

type CreateStockTags201JSONResponse TagID

func (response CreateStockTags201JSONResponse) VisitCreateStockTagsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateStockTags400JSONResponse Error

func (response CreateStockTags400JSONResponse) VisitCreateStockTagsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateStockTags500JSONResponse Error

func (response CreateStockTags500JSONResponse) VisitCreateStockTagsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteStockTagRequestObject struct {
	Id TagIDParam `json:"id"`
}

type DeleteStockTagResponseObject interface {
	VisitDeleteStockTagResponse(w http.ResponseWriter) error
}

type DeleteStockTag204Response struct {
}

func (response DeleteStockTag204Response) VisitDeleteStockTagResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteStockTag400JSONResponse Error

func (response DeleteStockTag400JSONResponse) VisitDeleteStockTagResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteStockTag404JSONResponse Error

func (response DeleteStockTag404JSONResponse) VisitDeleteStockTagResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteStockTag500JSONResponse Error

func (response DeleteStockTag500JSONResponse) VisitDeleteStockTagResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetStockTagRequestObject struct {
	Id TagIDParam `json:"id"`
}

type GetStockTagResponseObject interface {
	VisitGetStockTagResponse(w http.ResponseWriter) error
}

type GetStockTag200JSONResponse TagData

func (response GetStockTag200JSONResponse) VisitGetStockTagResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetStockTag400JSONResponse Error

func (response GetStockTag400JSONResponse) VisitGetStockTagResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetStockTag404JSONResponse Error

func (response GetStockTag404JSONResponse) VisitGetStockTagResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetStockTag500JSONResponse Error

func (response GetStockTag500JSONResponse) VisitGetStockTagResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateStockTagRequestObject struct {
	Id   TagIDParam `json:"id"`
	Body *UpdateStockTagJSONRequestBody
}

type UpdateStockTagResponseObject interface {
	VisitUpdateStockTagResponse(w http.ResponseWriter) error
}

type UpdateStockTag204Response struct {
}

func (response UpdateStockTag204Response) VisitUpdateStockTagResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type UpdateStockTag400JSONResponse Error

func (response UpdateStockTag400JSONResponse) VisitUpdateStockTagResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateStockTag404JSONResponse Error

func (response UpdateStockTag404JSONResponse) VisitUpdateStockTagResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateStockTag500JSONResponse Error

func (response UpdateStockTag500JSONResponse) VisitUpdateStockTagResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteStockRequestObject struct {
	Id StockIDParam `json:"id"`
}

type DeleteStockResponseObject interface {
	VisitDeleteStockResponse(w http.ResponseWriter) error
}

type DeleteStock204Response struct {
}

func (response DeleteStock204Response) VisitDeleteStockResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteStock400JSONResponse Error

func (response DeleteStock400JSONResponse) VisitDeleteStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteStock404JSONResponse Error

func (response DeleteStock404JSONResponse) VisitDeleteStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteStock500JSONResponse Error

func (response DeleteStock500JSONResponse) VisitDeleteStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetStockRequestObject struct {
	Id StockIDParam `json:"id"`
}

type GetStockResponseObject interface {
	VisitGetStockResponse(w http.ResponseWriter) error
}

type GetStock200JSONResponse StockData

func (response GetStock200JSONResponse) VisitGetStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetStock400JSONResponse Error

func (response GetStock400JSONResponse) VisitGetStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetStock404JSONResponse Error

func (response GetStock404JSONResponse) VisitGetStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetStock500JSONResponse Error

func (response GetStock500JSONResponse) VisitGetStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateStockRequestObject struct {
	Id   StockIDParam `json:"id"`
	Body *UpdateStockJSONRequestBody
}

type UpdateStockResponseObject interface {
	VisitUpdateStockResponse(w http.ResponseWriter) error
}

type UpdateStock204Response struct {
}

func (response UpdateStock204Response) VisitUpdateStockResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type UpdateStock400JSONResponse Error

func (response UpdateStock400JSONResponse) VisitUpdateStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateStock404JSONResponse Error

func (response UpdateStock404JSONResponse) VisitUpdateStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateStock500JSONResponse Error

func (response UpdateStock500JSONResponse) VisitUpdateStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// HealthCheck Health Check
	// (GET /health)
	HealthCheck(ctx context.Context, request HealthCheckRequestObject) (HealthCheckResponseObject, error)
	// ListStocks List
	// (GET /stocks)
	ListStocks(ctx context.Context, request ListStocksRequestObject) (ListStocksResponseObject, error)
	// CreateStock Create
	// (POST /stocks)
	CreateStock(ctx context.Context, request CreateStockRequestObject) (CreateStockResponseObject, error)
	// ListStockTags List
	// (GET /stocks/tags)
	ListStockTags(ctx context.Context, request ListStockTagsRequestObject) (ListStockTagsResponseObject, error)
	// CreateStockTags Create
	// (POST /stocks/tags)
	CreateStockTags(ctx context.Context, request CreateStockTagsRequestObject) (CreateStockTagsResponseObject, error)
	// DeleteStockTag Delete
	// (DELETE /stocks/tags/{id})
	DeleteStockTag(ctx context.Context, request DeleteStockTagRequestObject) (DeleteStockTagResponseObject, error)
	// GetStockTag Get
	// (GET /stocks/tags/{id})
	GetStockTag(ctx context.Context, request GetStockTagRequestObject) (GetStockTagResponseObject, error)
	// UpdateStockTag Update
	// (PUT /stocks/tags/{id})
	UpdateStockTag(ctx context.Context, request UpdateStockTagRequestObject) (UpdateStockTagResponseObject, error)
	// DeleteStock Delete
	// (DELETE /stocks/{id})
	DeleteStock(ctx context.Context, request DeleteStockRequestObject) (DeleteStockResponseObject, error)
	// GetStock Get
	// (GET /stocks/{id})
	GetStock(ctx context.Context, request GetStockRequestObject) (GetStockResponseObject, error)
	// UpdateStock Update
	// (PUT /stocks/{id})
	UpdateStock(ctx context.Context, request UpdateStockRequestObject) (UpdateStockResponseObject, error)
}

type StrictHandlerFunc func(ctx *echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// HealthCheck operation middleware
func (sh *strictHandler) HealthCheck(ctx *echo.Context) error {
	var request HealthCheckRequestObject

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.HealthCheck(ctx.Request().Context(), request.(HealthCheckRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HealthCheck")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(HealthCheckResponseObject); ok {
		return validResponse.VisitHealthCheckResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListStocks operation middleware
func (sh *strictHandler) ListStocks(ctx *echo.Context) error {
	var request ListStocksRequestObject

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListStocks(ctx.Request().Context(), request.(ListStocksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListStocks")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListStocksResponseObject); ok {
		return validResponse.VisitListStocksResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateStock operation middleware
func (sh *strictHandler) CreateStock(ctx *echo.Context) error {
	var request CreateStockRequestObject

	var body CreateStockJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateStock(ctx.Request().Context(), request.(CreateStockRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateStock")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateStockResponseObject); ok {
		return validResponse.VisitCreateStockResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListStockTags operation middleware
func (sh *strictHandler) ListStockTags(ctx *echo.Context) error {
	var request ListStockTagsRequestObject

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListStockTags(ctx.Request().Context(), request.(ListStockTagsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListStockTags")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListStockTagsResponseObject); ok {
		return validResponse.VisitListStockTagsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateStockTags operation middleware
func (sh *strictHandler) CreateStockTags(ctx *echo.Context) error {
	var request CreateStockTagsRequestObject

	var body CreateStockTagsJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateStockTags(ctx.Request().Context(), request.(CreateStockTagsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateStockTags")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateStockTagsResponseObject); ok {
		return validResponse.VisitCreateStockTagsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteStockTag operation middleware
func (sh *strictHandler) DeleteStockTag(ctx *echo.Context, id TagIDParam) error {
	var request DeleteStockTagRequestObject

	request.Id = id

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteStockTag(ctx.Request().Context(), request.(DeleteStockTagRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteStockTag")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteStockTagResponseObject); ok {
		return validResponse.VisitDeleteStockTagResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetStockTag operation middleware
func (sh *strictHandler) GetStockTag(ctx *echo.Context, id TagIDParam) error {
	var request GetStockTagRequestObject

	request.Id = id

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetStockTag(ctx.Request().Context(), request.(GetStockTagRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetStockTag")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetStockTagResponseObject); ok {
		return validResponse.VisitGetStockTagResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateStockTag operation middleware
func (sh *strictHandler) UpdateStockTag(ctx *echo.Context, id TagIDParam) error {
	var request UpdateStockTagRequestObject

	request.Id = id

	var body UpdateStockTagJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateStockTag(ctx.Request().Context(), request.(UpdateStockTagRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateStockTag")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateStockTagResponseObject); ok {
		return validResponse.VisitUpdateStockTagResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteStock operation middleware
func (sh *strictHandler) DeleteStock(ctx *echo.Context, id StockIDParam) error {
	var request DeleteStockRequestObject

	request.Id = id

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteStock(ctx.Request().Context(), request.(DeleteStockRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteStock")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteStockResponseObject); ok {
		return validResponse.VisitDeleteStockResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetStock operation middleware
func (sh *strictHandler) GetStock(ctx *echo.Context, id StockIDParam) error {
	var request GetStockRequestObject

	request.Id = id

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetStock(ctx.Request().Context(), request.(GetStockRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetStock")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetStockResponseObject); ok {
		return validResponse.VisitGetStockResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateStock operation middleware
func (sh *strictHandler) UpdateStock(ctx *echo.Context, id StockIDParam) error {
	var request UpdateStockRequestObject

	request.Id = id

	var body UpdateStockJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateStock(ctx.Request().Context(), request.(UpdateStockRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateStock")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateStockResponseObject); ok {
		return validResponse.VisitUpdateStockResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FpLc+M2Ev4rKGyq9kKKTz1v84ozVd5saj1zmvUBBJoSYhJgANCOVqX/vgWQepmUrWSkGe/GR5Ld6O6v",
	"v36I1ApTWVZSgDAaz1a4IoqUYEC5qxsj6d3H97/Ym/YafidlVQCe4ck4oTQLcx/GeeqnLI79aRrHPkyy",
	"LEsmyTAlQ+xhLvAMV8QssIcFKa0mZ9jDCn6ruQKGZ0bV4GFNF1ASayKXqiQGz3BdO0mzrKyWNoqLOV6v",
	"PfyJzHtdSodhHGVT8JMkpH5KotyfTCPqp+FonJMsHtMsvIhL642ww+yDUlIdeLbCJWhN5lbpLWHoX/Bb",
	"DdrgtYcrJStQhoM+EFv1hL3z78tW8HbrjMx+BeqOdDl7Twx55AOtlQJBl3iGf8De9vLD70328Sz2MANN",
	"Fa8MlxakcolKwgXKiLjDHl4Q/aaUtRVtEGrRs4/RW4sLmWvr3YmJSGgYsfFo6NMRYX6axolPJtPEz4dT",
	"iEdDmoQswR6ejLOQEhb5oyiM/HQySvzpCKb+MKJxlk+T6Tih+LaD5S7cDph9we9lmQuTxNjDJRe8rEs8",
	"C7coc2FgDsoecQBVj4k9tLZPMykLIMI+brBbWSPXIOZmgWeR1z2lgXSFuYFSn8DF7Q2iFFl2eOOs7vu2",
	"g6KPEodRtt4c5dzH948Yx9mpjaKTPat6Si/YD46z477pA9e+nFYNHcK7gCgdjtmITf2chamf5tPIn8Iw",
	"81NI0mg8CSHNxviwON7gtfc1JkOSQzYNE59N4sRPUzL2sxRyPwyjMYzjjLAh25ksl+iBFAWYr7SaMRhO",
	"plnqj4fD0E+HNPVJOGI+AzJNIojTMIl2VmVt8PrW2zH125bjM+V2Ep9OrMou7bw/Wlh9PD0sXDfmerr4",
	"Hq10t2z+jP9Op88hN2f7Svqk/n7Jkv7UdsX9gj7dM+8xiK3yifOoVWaEF0tUa9gdcNKk2h6gyT0Xc31Y",
	"NKQo/pm7eH5QkOMZ/luw28+CdssImsxYu89IOQJZA/2EfZ6GNiFc5NKVsBSGUFdgtSrwDC+MqfQsCObc",
	"LOpsQGUZ/MP/iaj6jge5LoD1jUr8Bi34fFEsEa21kSX/D8kKQBUoLQUpUKOGMqKBISmQWQD6sZAP6N91",
	"GMYj5No5KiWDYoA9XHAKQu+XxtXPn9GbPAcl0RUIUKRAv9RZwSm6bmTRfTKwLDg9iCArZBbYXSi4/vju",
	"w883HxxS3Li988eb6yZUD9+D0k2U4SAcRFZKViBIxS2/BpGza3dPl+xgAaSwNbrCc3C4dpByAogugN4h",
	"EKySXBiUS4WYpHegLAK2xojV+Gg5+JPTeGcV3E6rKyl0U4BxmHZtNPLLgXV1GCabPLdNmFRVwak7PfhV",
	"N5vObi9+inzNFuz4c2jws1hsTdrFGWituFni2ZdbD+u6LIlabv1Cm0A2qyWVZSkFvrWqgd5O9l74rsAg",
	"UhSoEfs74gwRwZClSRe3a65Nuyl0YAvPhkproQeWBv/w8vjfgLoHhTbPj2fAIrKHvEOx2bOl7kH7nQJi",
	"AAl4aAC3hSvQHAyi7glrb3PWBb/RdeC0P8RAm7eSLc8LfNMND2eM3XfWnYxH5zVsm3U3E03UzJVe+i1S",
	"/+i358uiW4NGD+F2lR5sfg09We5W6In6drvDBUvcnX+kwF+z/OeaCnFtxZD5k61jm9nzt4/tKvVtm0e7",
	"5722jvO0jmDF2bohWQEGunR77+4j0k+15umGam6R270rPbKx70SCvdeWzUb+3GrW2Pt+SU4bpy5r89MC",
	"2sVASLvZ1oINXh7DmlT0Nq7js6ifRVdgLkSh8DLt7mWMsVcybsl4BUdGaN03QRdEzI+2tM8VI+dsad95",
	"8qbH4n9toi+Atw3Znh7TJ09oJ//kjP7DbD742Pk6ov8CI7qJioEhvNDHR/XZmRRe6r3G66z+v5jVR5rb",
	"3rQ+ByW/+1u213H9vzmunZI9pWHe4fkM7qGQFQJxz5UUZfM/gt23llkQFJKSYiG1mUVJnASk4o6RrZ3H",
	"B+qW75vPZu5y7T0WM4oITWj7T4VWeP9mVyUv5MNO1l11hdovDlux9np9u/5vAAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
