// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for TagType.
const (
	TagTypeFlows        TagType = "flows"
	TagTypeStocks       TagType = "stocks"
	TagTypeTransactions TagType = "transactions"
)

// Valid indicates whether the value is a known member of the TagType enum.
func (e TagType) Valid() bool {
	switch e {
	case TagTypeFlows:
		return true
	case TagTypeStocks:
		return true
	case TagTypeTransactions:
		return true
	default:
		return false
	}
}

// Defines values for ListTagsParamsType.
const (
	ListTagsParamsTypeFlows        ListTagsParamsType = "flows"
	ListTagsParamsTypeStocks       ListTagsParamsType = "stocks"
	ListTagsParamsTypeTransactions ListTagsParamsType = "transactions"
)

// Valid indicates whether the value is a known member of the ListTagsParamsType enum.
func (e ListTagsParamsType) Valid() bool {
	switch e {
	case ListTagsParamsTypeFlows:
		return true
	case ListTagsParamsTypeStocks:
		return true
	case ListTagsParamsTypeTransactions:
		return true
	default:
		return false
	}
}

// Defines values for CreateTagsParamsType.
const (
	CreateTagsParamsTypeFlows        CreateTagsParamsType = "flows"
	CreateTagsParamsTypeStocks       CreateTagsParamsType = "stocks"
	CreateTagsParamsTypeTransactions CreateTagsParamsType = "transactions"
)

// Valid indicates whether the value is a known member of the CreateTagsParamsType enum.
func (e CreateTagsParamsType) Valid() bool {
	switch e {
	case CreateTagsParamsTypeFlows:
		return true
	case CreateTagsParamsTypeStocks:
		return true
	case CreateTagsParamsTypeTransactions:
		return true
	default:
		return false
	}
}

// Defines values for DeleteTagParamsType.
const (
	DeleteTagParamsTypeFlows        DeleteTagParamsType = "flows"
	DeleteTagParamsTypeStocks       DeleteTagParamsType = "stocks"
	DeleteTagParamsTypeTransactions DeleteTagParamsType = "transactions"
)

// Valid indicates whether the value is a known member of the DeleteTagParamsType enum.
func (e DeleteTagParamsType) Valid() bool {
	switch e {
	case DeleteTagParamsTypeFlows:
		return true
	case DeleteTagParamsTypeStocks:
		return true
	case DeleteTagParamsTypeTransactions:
		return true
	default:
		return false
	}
}

// Defines values for GetTagParamsType.
const (
	GetTagParamsTypeFlows        GetTagParamsType = "flows"
	GetTagParamsTypeStocks       GetTagParamsType = "stocks"
	GetTagParamsTypeTransactions GetTagParamsType = "transactions"
)

// Valid indicates whether the value is a known member of the GetTagParamsType enum.
func (e GetTagParamsType) Valid() bool {
	switch e {
	case GetTagParamsTypeFlows:
		return true
	case GetTagParamsTypeStocks:
		return true
	case GetTagParamsTypeTransactions:
		return true
	default:
		return false
	}
}

// Defines values for UpdateTagParamsType.
const (
	UpdateTagParamsTypeFlows        UpdateTagParamsType = "flows"
	UpdateTagParamsTypeStocks       UpdateTagParamsType = "stocks"
	UpdateTagParamsTypeTransactions UpdateTagParamsType = "transactions"
)

// Valid indicates whether the value is a known member of the UpdateTagParamsType enum.
func (e UpdateTagParamsType) Valid() bool {
	switch e {
	case UpdateTagParamsTypeFlows:
		return true
	case UpdateTagParamsTypeStocks:
		return true
	case UpdateTagParamsTypeTransactions:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// StockBase defines model for StockBase.
type StockBase struct {
	Currency    string `json:"currency"`
	Description string `json:"description"`
	HasAmount   bool   `json:"has_amount"`
	Name        string `json:"name"`
}

// StockData defines model for StockData.
type StockData struct {
	Currency    string               `json:"currency"`
	Description string               `json:"description"`
	HasAmount   bool                 `json:"has_amount"`
	Name        string               `json:"name"`
	Tags        []openapi_types.UUID `json:"tags"`
}

// StockGetData defines model for StockGetData.
type StockGetData struct {
	Currency    string `json:"currency"`
	Description string `json:"description"`
	HasAmount   bool   `json:"has_amount"`
	Name        string `json:"name"`
	Tags        Tags   `json:"tags"`
}

// StockID defines model for StockID.
type StockID struct {
	Id openapi_types.UUID `json:"id"`
}

// Stocks defines model for Stocks.
type Stocks = []struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
}

// TagData defines model for TagData.
type TagData struct {
	Name string `json:"name"`
}

// TagID defines model for TagID.
type TagID struct {
	Id openapi_types.UUID `json:"id"`
}

// Tags defines model for Tags.
type Tags = []struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
}

// StockIDParam defines model for StockIDParam.
type StockIDParam = openapi_types.UUID

// TagIDParam defines model for TagIDParam.
type TagIDParam = openapi_types.UUID

// TagType defines model for TagType.
type TagType string

// ListTagsParamsType defines parameters for ListTags.
type ListTagsParamsType string

// CreateTagsParamsType defines parameters for CreateTags.
type CreateTagsParamsType string

// DeleteTagParamsType defines parameters for DeleteTag.
type DeleteTagParamsType string

// GetTagParamsType defines parameters for GetTag.
type GetTagParamsType string

// UpdateTagParamsType defines parameters for UpdateTag.
type UpdateTagParamsType string

// CreateStockJSONRequestBody defines body for CreateStock for application/json ContentType.
type CreateStockJSONRequestBody = StockData

// UpdateStockJSONRequestBody defines body for UpdateStock for application/json ContentType.
type UpdateStockJSONRequestBody = StockData

// CreateTagsJSONRequestBody defines body for CreateTags for application/json ContentType.
type CreateTagsJSONRequestBody = TagData

// UpdateTagJSONRequestBody defines body for UpdateTag for application/json ContentType.
type UpdateTagJSONRequestBody = TagData

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// HealthCheck Health Check
	// (GET /health)
	HealthCheck(ctx *echo.Context) error
	// ListStocks List
	// (GET /stocks)
	ListStocks(ctx *echo.Context) error
	// CreateStock Create
	// (POST /stocks)
	CreateStock(ctx *echo.Context) error
	// DeleteStock Delete
	// (DELETE /stocks/{id})
	DeleteStock(ctx *echo.Context, id StockIDParam) error
	// GetStock Get
	// (GET /stocks/{id})
	GetStock(ctx *echo.Context, id StockIDParam) error
	// UpdateStock Update
	// (PUT /stocks/{id})
	UpdateStock(ctx *echo.Context, id StockIDParam) error
	// ListTags List
	// (GET /tags/{type})
	ListTags(ctx *echo.Context, pType ListTagsParamsType) error
	// CreateTags Create
	// (POST /tags/{type})
	CreateTags(ctx *echo.Context, pType CreateTagsParamsType) error
	// DeleteTag Delete
	// (DELETE /tags/{type}/{id})
	DeleteTag(ctx *echo.Context, pType DeleteTagParamsType, id TagIDParam) error
	// GetTag Get
	// (GET /tags/{type}/{id})
	GetTag(ctx *echo.Context, pType GetTagParamsType, id TagIDParam) error
	// UpdateTag Update
	// (PUT /tags/{type}/{id})
	UpdateTag(ctx *echo.Context, pType UpdateTagParamsType, id TagIDParam) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// HealthCheck converts echo context to params.
func (w *ServerInterfaceWrapper) HealthCheck(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.HealthCheck(ctx)
	return err
}

// ListStocks converts echo context to params.
func (w *ServerInterfaceWrapper) ListStocks(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListStocks(ctx)
	return err
}

// CreateStock converts echo context to params.
func (w *ServerInterfaceWrapper) CreateStock(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateStock(ctx)
	return err
}

// DeleteStock converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteStock(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id StockIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteStock(ctx, id)
	return err
}

// GetStock converts echo context to params.
func (w *ServerInterfaceWrapper) GetStock(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id StockIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetStock(ctx, id)
	return err
}

// UpdateStock converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateStock(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id StockIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateStock(ctx, id)
	return err
}

// ListTags converts echo context to params.
func (w *ServerInterfaceWrapper) ListTags(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "type" -------------
	var pType ListTagsParamsType

	err = runtime.BindStyledParameterWithOptions("simple", "type", ctx.Param("type"), &pType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter type: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListTags(ctx, pType)
	return err
}

// CreateTags converts echo context to params.
func (w *ServerInterfaceWrapper) CreateTags(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "type" -------------
	var pType CreateTagsParamsType

	err = runtime.BindStyledParameterWithOptions("simple", "type", ctx.Param("type"), &pType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter type: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateTags(ctx, pType)
	return err
}

// DeleteTag converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteTag(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "type" -------------
	var pType DeleteTagParamsType

	err = runtime.BindStyledParameterWithOptions("simple", "type", ctx.Param("type"), &pType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter type: %s", err))
	}

	// ------------- Path parameter "id" -------------
	var id TagIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteTag(ctx, pType, id)
	return err
}

// GetTag converts echo context to params.
func (w *ServerInterfaceWrapper) GetTag(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "type" -------------
	var pType GetTagParamsType

	err = runtime.BindStyledParameterWithOptions("simple", "type", ctx.Param("type"), &pType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter type: %s", err))
	}

	// ------------- Path parameter "id" -------------
	var id TagIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTag(ctx, pType, id)
	return err
}

// UpdateTag converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateTag(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "type" -------------
	var pType UpdateTagParamsType

	err = runtime.BindStyledParameterWithOptions("simple", "type", ctx.Param("type"), &pType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter type: %s", err))
	}

	// ------------- Path parameter "id" -------------
	var id TagIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateTag(ctx, pType, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/health", wrapper.HealthCheck, options.OperationMiddlewares["healthCheck"]...)
	router.GET(options.BaseURL+"/stocks", wrapper.ListStocks, options.OperationMiddlewares["listStocks"]...)
	router.POST(options.BaseURL+"/stocks", wrapper.CreateStock, options.OperationMiddlewares["createStock"]...)
	router.DELETE(options.BaseURL+"/stocks/:id", wrapper.DeleteStock, options.OperationMiddlewares["deleteStock"]...)
	router.GET(options.BaseURL+"/stocks/:id", wrapper.GetStock, options.OperationMiddlewares["getStock"]...)
	router.PUT(options.BaseURL+"/stocks/:id", wrapper.UpdateStock, options.OperationMiddlewares["updateStock"]...)
	router.GET(options.BaseURL+"/tags/:type", wrapper.ListTags, options.OperationMiddlewares["listTags"]...)
	router.POST(options.BaseURL+"/tags/:type", wrapper.CreateTags, options.OperationMiddlewares["createTags"]...)
	router.DELETE(options.BaseURL+"/tags/:type/:id", wrapper.DeleteTag, options.OperationMiddlewares["deleteTag"]...)
	router.GET(options.BaseURL+"/tags/:type/:id", wrapper.GetTag, options.OperationMiddlewares["getTag"]...)
	router.PUT(options.BaseURL+"/tags/:type/:id", wrapper.UpdateTag, options.OperationMiddlewares["updateTag"]...)

}

type HealthCheckRequestObject struct {
}

type HealthCheckResponseObject interface {
	VisitHealthCheckResponse(w http.ResponseWriter) error
}

type HealthCheck204Response struct {
}

func (response HealthCheck204Response) VisitHealthCheckResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type HealthCheck503JSONResponse Error

func (response HealthCheck503JSONResponse) VisitHealthCheckResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type ListStocksRequestObject struct {
}

type ListStocksResponseObject interface {
	VisitListStocksResponse(w http.ResponseWriter) error
}

type ListStocks200JSONResponse Stocks

func (response ListStocks200JSONResponse) VisitListStocksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListStocks500JSONResponse Error

func (response ListStocks500JSONResponse) VisitListStocksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateStockRequestObject struct {
	Body *CreateStockJSONRequestBody
}

type CreateStockResponseObject interface {
	VisitCreateStockResponse(w http.ResponseWriter) error
}

type CreateStock201JSONResponse StockID

func (response CreateStock201JSONResponse) VisitCreateStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateStock400JSONResponse Error

func (response CreateStock400JSONResponse) VisitCreateStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateStock500JSONResponse Error

func (response CreateStock500JSONResponse) VisitCreateStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteStockRequestObject struct {
	Id StockIDParam `json:"id"`
}

type DeleteStockResponseObject interface {
	VisitDeleteStockResponse(w http.ResponseWriter) error
}

type DeleteStock204Response struct {
}

func (response DeleteStock204Response) VisitDeleteStockResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteStock400JSONResponse Error

func (response DeleteStock400JSONResponse) VisitDeleteStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteStock404JSONResponse Error

func (response DeleteStock404JSONResponse) VisitDeleteStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteStock500JSONResponse Error

func (response DeleteStock500JSONResponse) VisitDeleteStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetStockRequestObject struct {
	Id StockIDParam `json:"id"`
}

type GetStockResponseObject interface {
	VisitGetStockResponse(w http.ResponseWriter) error
}

type GetStock200JSONResponse StockGetData

func (response GetStock200JSONResponse) VisitGetStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetStock400JSONResponse Error

func (response GetStock400JSONResponse) VisitGetStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetStock404JSONResponse Error

func (response GetStock404JSONResponse) VisitGetStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetStock500JSONResponse Error

func (response GetStock500JSONResponse) VisitGetStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateStockRequestObject struct {
	Id   StockIDParam `json:"id"`
	Body *UpdateStockJSONRequestBody
}

type UpdateStockResponseObject interface {
	VisitUpdateStockResponse(w http.ResponseWriter) error
}

type UpdateStock204Response struct {
}

func (response UpdateStock204Response) VisitUpdateStockResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type UpdateStock400JSONResponse Error

func (response UpdateStock400JSONResponse) VisitUpdateStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateStock404JSONResponse Error

func (response UpdateStock404JSONResponse) VisitUpdateStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateStock500JSONResponse Error

func (response UpdateStock500JSONResponse) VisitUpdateStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListTagsRequestObject struct {
	Type ListTagsParamsType `json:"type"`
}

type ListTagsResponseObject interface {
	VisitListTagsResponse(w http.ResponseWriter) error
}

type ListTags200JSONResponse Tags

func (response ListTags200JSONResponse) VisitListTagsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListTags400JSONResponse Error

func (response ListTags400JSONResponse) VisitListTagsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListTags500JSONResponse Error

func (response ListTags500JSONResponse) VisitListTagsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTagsRequestObject struct {
	Type CreateTagsParamsType `json:"type"`
	Body *CreateTagsJSONRequestBody
}

type CreateTagsResponseObject interface {
	VisitCreateTagsResponse(w http.ResponseWriter) error
}

type CreateTags201JSONResponse TagID

func (response CreateTags201JSONResponse) VisitCreateTagsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTags400JSONResponse Error

func (response CreateTags400JSONResponse) VisitCreateTagsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTags500JSONResponse Error

func (response CreateTags500JSONResponse) VisitCreateTagsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteTagRequestObject struct {
	Type DeleteTagParamsType `json:"type"`
	Id   TagIDParam          `json:"id"`
}

type DeleteTagResponseObject interface {
	VisitDeleteTagResponse(w http.ResponseWriter) error
}

type DeleteTag204Response struct {
}

func (response DeleteTag204Response) VisitDeleteTagResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteTag400JSONResponse Error

func (response DeleteTag400JSONResponse) VisitDeleteTagResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteTag404JSONResponse Error

func (response DeleteTag404JSONResponse) VisitDeleteTagResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteTag500JSONResponse Error

func (response DeleteTag500JSONResponse) VisitDeleteTagResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetTagRequestObject struct {
	Type GetTagParamsType `json:"type"`
	Id   TagIDParam       `json:"id"`
}

type GetTagResponseObject interface {
	VisitGetTagResponse(w http.ResponseWriter) error
}

type GetTag200JSONResponse TagData

func (response GetTag200JSONResponse) VisitGetTagResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetTag400JSONResponse Error

func (response GetTag400JSONResponse) VisitGetTagResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetTag404JSONResponse Error

func (response GetTag404JSONResponse) VisitGetTagResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetTag500JSONResponse Error

func (response GetTag500JSONResponse) VisitGetTagResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateTagRequestObject struct {
	Type UpdateTagParamsType `json:"type"`
	Id   TagIDParam          `json:"id"`
	Body *UpdateTagJSONRequestBody
}

type UpdateTagResponseObject interface {
	VisitUpdateTagResponse(w http.ResponseWriter) error
}

type UpdateTag204Response struct {
}

func (response UpdateTag204Response) VisitUpdateTagResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type UpdateTag400JSONResponse Error

func (response UpdateTag400JSONResponse) VisitUpdateTagResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateTag404JSONResponse Error

func (response UpdateTag404JSONResponse) VisitUpdateTagResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateTag500JSONResponse Error

func (response UpdateTag500JSONResponse) VisitUpdateTagResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// HealthCheck Health Check
	// (GET /health)
	HealthCheck(ctx context.Context, request HealthCheckRequestObject) (HealthCheckResponseObject, error)
	// ListStocks List
	// (GET /stocks)
	ListStocks(ctx context.Context, request ListStocksRequestObject) (ListStocksResponseObject, error)
	// CreateStock Create
	// (POST /stocks)
	CreateStock(ctx context.Context, request CreateStockRequestObject) (CreateStockResponseObject, error)
	// DeleteStock Delete
	// (DELETE /stocks/{id})
	DeleteStock(ctx context.Context, request DeleteStockRequestObject) (DeleteStockResponseObject, error)
	// GetStock Get
	// (GET /stocks/{id})
	GetStock(ctx context.Context, request GetStockRequestObject) (GetStockResponseObject, error)
	// UpdateStock Update
	// (PUT /stocks/{id})
	UpdateStock(ctx context.Context, request UpdateStockRequestObject) (UpdateStockResponseObject, error)
	// ListTags List
	// (GET /tags/{type})
	ListTags(ctx context.Context, request ListTagsRequestObject) (ListTagsResponseObject, error)
	// CreateTags Create
	// (POST /tags/{type})
	CreateTags(ctx context.Context, request CreateTagsRequestObject) (CreateTagsResponseObject, error)
	// DeleteTag Delete
	// (DELETE /tags/{type}/{id})
	DeleteTag(ctx context.Context, request DeleteTagRequestObject) (DeleteTagResponseObject, error)
	// GetTag Get
	// (GET /tags/{type}/{id})
	GetTag(ctx context.Context, request GetTagRequestObject) (GetTagResponseObject, error)
	// UpdateTag Update
	// (PUT /tags/{type}/{id})
	UpdateTag(ctx context.Context, request UpdateTagRequestObject) (UpdateTagResponseObject, error)
}

type StrictHandlerFunc func(ctx *echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// HealthCheck operation middleware
func (sh *strictHandler) HealthCheck(ctx *echo.Context) error {
	var request HealthCheckRequestObject

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.HealthCheck(ctx.Request().Context(), request.(HealthCheckRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HealthCheck")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(HealthCheckResponseObject); ok {
		return validResponse.VisitHealthCheckResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListStocks operation middleware
func (sh *strictHandler) ListStocks(ctx *echo.Context) error {
	var request ListStocksRequestObject

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListStocks(ctx.Request().Context(), request.(ListStocksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListStocks")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListStocksResponseObject); ok {
		return validResponse.VisitListStocksResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateStock operation middleware
func (sh *strictHandler) CreateStock(ctx *echo.Context) error {
	var request CreateStockRequestObject

	var body CreateStockJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateStock(ctx.Request().Context(), request.(CreateStockRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateStock")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateStockResponseObject); ok {
		return validResponse.VisitCreateStockResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteStock operation middleware
func (sh *strictHandler) DeleteStock(ctx *echo.Context, id StockIDParam) error {
	var request DeleteStockRequestObject

	request.Id = id

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteStock(ctx.Request().Context(), request.(DeleteStockRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteStock")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteStockResponseObject); ok {
		return validResponse.VisitDeleteStockResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetStock operation middleware
func (sh *strictHandler) GetStock(ctx *echo.Context, id StockIDParam) error {
	var request GetStockRequestObject

	request.Id = id

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetStock(ctx.Request().Context(), request.(GetStockRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetStock")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetStockResponseObject); ok {
		return validResponse.VisitGetStockResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateStock operation middleware
func (sh *strictHandler) UpdateStock(ctx *echo.Context, id StockIDParam) error {
	var request UpdateStockRequestObject

	request.Id = id

	var body UpdateStockJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateStock(ctx.Request().Context(), request.(UpdateStockRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateStock")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateStockResponseObject); ok {
		return validResponse.VisitUpdateStockResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListTags operation middleware
func (sh *strictHandler) ListTags(ctx *echo.Context, pType ListTagsParamsType) error {
	var request ListTagsRequestObject

	request.Type = pType

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListTags(ctx.Request().Context(), request.(ListTagsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTags")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListTagsResponseObject); ok {
		return validResponse.VisitListTagsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateTags operation middleware
func (sh *strictHandler) CreateTags(ctx *echo.Context, pType CreateTagsParamsType) error {
	var request CreateTagsRequestObject

	request.Type = pType

	var body CreateTagsJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTags(ctx.Request().Context(), request.(CreateTagsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTags")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateTagsResponseObject); ok {
		return validResponse.VisitCreateTagsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteTag operation middleware
func (sh *strictHandler) DeleteTag(ctx *echo.Context, pType DeleteTagParamsType, id TagIDParam) error {
	var request DeleteTagRequestObject

	request.Type = pType
	request.Id = id

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteTag(ctx.Request().Context(), request.(DeleteTagRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteTag")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteTagResponseObject); ok {
		return validResponse.VisitDeleteTagResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetTag operation middleware
func (sh *strictHandler) GetTag(ctx *echo.Context, pType GetTagParamsType, id TagIDParam) error {
	var request GetTagRequestObject

	request.Type = pType
	request.Id = id

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetTag(ctx.Request().Context(), request.(GetTagRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTag")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetTagResponseObject); ok {
		return validResponse.VisitGetTagResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateTag operation middleware
func (sh *strictHandler) UpdateTag(ctx *echo.Context, pType UpdateTagParamsType, id TagIDParam) error {
	var request UpdateTagRequestObject

	request.Type = pType
	request.Id = id

	var body UpdateTagJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateTag(ctx.Request().Context(), request.(UpdateTagRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateTag")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateTagResponseObject); ok {
		return validResponse.VisitUpdateTagResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Frdc6M4Ev9XVLqtuhcIYPDn23xtdqpye1uXzNNc6kpIjc0GJFYSyflc/t+vJIGxA544U8kkU5VHoLvV",
	"/PrXX9gbTEVZCQ5cK7zY4IpIUoIGaa8utaA3nz/+YW6aa/gvKasC8ALPpjGlaZj5MM0SP2GjkT9PRiMf",
	"ZmmaxrN4nJAx9nDO8QJXRK+whzkpjWbOsIcl/FXnEhheaFmDhxVdQUnMEZmQJdF4gevaSup1ZbSUljlf",
	"4u3Ww1dkOehSMg5HUToHP45D6ickyvzZPKJ+Ek6mGUlHU5qGz+fSlb25748y4KnhE62Jb50JvC7x4mtn",
	"REvCFaE6F9xcZoW4U/i678y2tWID+ElKIQ/c2uASlCJLo/SeMPQv+KsGpfHWw5UUFUidgzoQ2wy8cOf4",
	"151g54xI/wRqTVoCvScK7vlAaymB0zVe4F+whxkoKvPKvBxe4HKNSpJzlBJ+gz28Iuo/pBQ11y1MDYjm",
	"OXrf97wz3nP93lEDz/dP2z1OhSiAcPPcnb3BZc4vgC/1Ci8i7wGErM6Baa9z8tCloyB+JNoSgxTFPzO8",
	"+LrBv0jI8AL/LegyOGhCH3S4b70D4DVZKuPSickS0zBi08nYpxPC/CQZxT6ZzWM/G89hNBnTOGQx9vBs",
	"moaUsMifRGHkJ7NJ7M8nMPfHER2l2TyeT2OKr3uBcs5scK6hVCdk2u4GkZKsezBbc30Ar1sIz0E/LYob",
	"UzlOLjx7rFXWoFU+EeFGmZG8WKO68cgaOAn7nQFFbnO+VA6V4Wh8C5ErI/NY3D9/vJf9jd8ndJCek0b1",
	"lIq871/OjqeVOnCtjSil4ymbsLmfsTDxk2we+XMYp34CcRJNZyEk6fQwouhdF5GQZJDOw9hns1HsJwmZ",
	"+mkCmR+G0RSmo5SwMeu0yzW6I0UBujOQMhjP5mniT8fj0E/GNPFJOGE+AzKPIxglYRx1BkRtwPa6LPoO",
	"xLq69iCUjegQoofZadtim3B70b+XB/fcPc2Poy7Y4WCIbicl6XPS7apJrx7Zfs7ysce304qpi4w59wEp",
	"SxlzwPcSzwQk55mws4DgmlDby2tZ4AVeaV2pRRAsc72q0zMqyuAf/m9E1jd5kKkC2BJkb07A79AqX66K",
	"NaK10qLM/0fSAlAFUglOCuTUUEoUMCQ40itAvxbiDv27DsPRBNlSg0rBoDjDHi5yClztJ8P571/QuywD",
	"KdA5cJCkQH/UaZFTdOFk0W18Zlhw+ksEaSHSwAxSwcXnD59+v/xkkcq1HU5/vbxwr+rhW5DKvWV4Fp5F",
	"RkpUwEmVG36dRfZcM77aYAcrIIWZejZ4CRbXHlJWANEV0BsEnFUi5xplQiIm6A1Ig4DJMWI0PhsO/mY1",
	"PhgFOxSrSnDlEnAUJv0znPz6zLg6DuM2zuBmNlJVRU6t9eBP5ca8brD+FvnctGz5c3jgF77aHWkGbKC1",
	"zPUaL75ee1jVZUnkeucXal+knbWoKEsz2hnVQO26ziB856ARKQrkxP6OcoYIZ8jQpI/bRa70Zbsg3IMt",
	"fDJUmhMGYHH4h8+P/yXIW5CofX48AgaRPeQtim7wFGoA7Q8SiAbE4c4BbhKXoyVoRO0T1tzOWR98p2vB",
	"aTY5UPq9YOunBd5Vw8MeY7agbS/i0dMebIp1PxLurZlNveRHhP7ejvq66ObQGCBcl+nBJmdbx7wCNPQ5",
	"+NHeR8RRrc8z97zl2f73mSMNtxMJDr7fuJb6UG39sCJ8+YIBTpxTz3vm1QqazObCtKaas7PXxy4X+cFy",
	"drR3uLdioEleqD6ZzkE/D5OeuN20q/qRpvNGzBcl5jkcabK1PlZQjte3LxUjT1jfXrwNv9XU10xdx7Yj",
	"HdvcCzZmmdw+OKAb2eGJ3C76j2Vy+wvCs5bW5uvdqympr3p30GT58OZA7O6gyfLYfvAEZHj6irb7yPJj",
	"14rmC9DbUvHIpcIx8V6BOn2vGGSne3pFlt9PTu8U0cctH86rt0b5GpePth4e74rDTDsH/aI0C5+nbL4t",
	"Ja96Kdl172+uJIOEdSPij+bsC3f5t63lp9pampHAqhgbjp6H1hncQiEqBPw2l4KXYP930v2AtAiCQlBS",
	"rITSiygexQGpcsvG3d8bDg2qZkdvfwu0l4brh2J7/1Ta+8PT3s2+SlaIu07WXg3YtRnZ2iPLAZHml5ad",
	"VHO9vd7+PwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
